#! /usr/bin/env php

<?php

// Pull in the autoload, so that all of the classes can be found
// NOTE: Cannot use any helper functions until after this file is pulled in
$loader = require_once __DIR__ . DIRECTORY_SEPARATOR . 'bootstrap' . DIRECTORY_SEPARATOR . 'autoload.php';

// Boot the generator
$generator = require_once build_path([
    __DIR__,
    'bootstrap',
    'generator.php'
]);

// Save the loader to the generator, so that we can add the generated folder late in the process
$generator->setLoader($loader);

// Make an application
$application = new Symfony\Component\Console\Application($generator->description(), $generator->version());

// Look up the commands & register them
$generator->registerCommandsWithApplication($application);

// Run the application
$application->run();
